notifications:
  email: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
# command to run tests
install: "pip install six coverage coveralls"
script: coverage run -m unittest -v tests.test_limigrations
after_success: coveralls